// <auto-generated />
using System;
using BooksSpotLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksSpotLibrary.Migrations
{
    [DbContext(typeof(BooksSpotLibraryContext))]
    [Migration("20220922142447_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BooksSpotLibrary.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Borrower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBNCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e38e1cf4-2cac-41d3-8a00-f3d6d094b33d"),
                            Author = "Author0",
                            Category = "Romance",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN016",
                            Publisher = "Publisher0",
                            PublishingDate = new DateTime(1957, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title0"
                        },
                        new
                        {
                            Id = new Guid("14e71586-aa89-4c69-8951-29c57d872932"),
                            Author = "Author1",
                            Category = "NonFiction",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN127",
                            Publisher = "Publisher1",
                            PublishingDate = new DateTime(1991, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title1"
                        },
                        new
                        {
                            Id = new Guid("036b1cf7-0ba6-474c-99fb-4f62a44e3a17"),
                            Author = "Author2",
                            Category = "Fantasy",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN238",
                            Publisher = "Publisher2",
                            PublishingDate = new DateTime(1967, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title2"
                        },
                        new
                        {
                            Id = new Guid("95de2b20-2952-45d1-ae6c-0bf780002e28"),
                            Author = "Author3",
                            Category = "ForChildren",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN349",
                            Publisher = "Publisher3",
                            PublishingDate = new DateTime(2009, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title3"
                        },
                        new
                        {
                            Id = new Guid("c46d6876-0e5d-4481-ba7c-b0874dcb09e0"),
                            Author = "Author4",
                            Category = "Drama",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN4510",
                            Publisher = "Publisher4",
                            PublishingDate = new DateTime(1958, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title4"
                        },
                        new
                        {
                            Id = new Guid("90323a81-e4f7-4dd9-91ef-e1c6d2634a5a"),
                            Author = "Author5",
                            Category = "Biography",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN5611",
                            Publisher = "Publisher5",
                            PublishingDate = new DateTime(1985, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title5"
                        },
                        new
                        {
                            Id = new Guid("a772e1de-9273-4b4f-86bc-fd4199661ca5"),
                            Author = "Author6",
                            Category = "Biography",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN6712",
                            Publisher = "Publisher6",
                            PublishingDate = new DateTime(1963, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title6"
                        },
                        new
                        {
                            Id = new Guid("d4c839de-c8f0-43a8-8fc8-2f314b20e94c"),
                            Author = "Author7",
                            Category = "NonFiction",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN7813",
                            Publisher = "Publisher7",
                            PublishingDate = new DateTime(2007, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title7"
                        },
                        new
                        {
                            Id = new Guid("3113406b-451e-4586-bfef-642ce499ae5a"),
                            Author = "Author8",
                            Category = "Crime",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN8914",
                            Publisher = "Publisher8",
                            PublishingDate = new DateTime(1957, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title8"
                        },
                        new
                        {
                            Id = new Guid("5241f82e-962c-43bb-88bc-e0013dabf66c"),
                            Author = "Author9",
                            Category = "ForTeens",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN91015",
                            Publisher = "Publisher9",
                            PublishingDate = new DateTime(1977, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title9"
                        },
                        new
                        {
                            Id = new Guid("02ae5870-c729-473b-9495-ab9a74be4056"),
                            Author = "Author10",
                            Category = "Poetry",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN101116",
                            Publisher = "Publisher10",
                            PublishingDate = new DateTime(1956, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title10"
                        },
                        new
                        {
                            Id = new Guid("6d7a271f-8d88-4be9-b62c-306cbd3d8643"),
                            Author = "Author11",
                            Category = "Horror",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN111217",
                            Publisher = "Publisher11",
                            PublishingDate = new DateTime(1980, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title11"
                        },
                        new
                        {
                            Id = new Guid("1274f244-26b4-4032-b7bc-234be873c937"),
                            Author = "Author12",
                            Category = "Biography",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN121318",
                            Publisher = "Publisher12",
                            PublishingDate = new DateTime(2017, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title12"
                        },
                        new
                        {
                            Id = new Guid("117dda17-7bb3-471d-bcf3-15bc9b122d09"),
                            Author = "Author13",
                            Category = "Poetry",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN131419",
                            Publisher = "Publisher13",
                            PublishingDate = new DateTime(1929, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title13"
                        },
                        new
                        {
                            Id = new Guid("856df689-c6ef-4d1f-9d8d-8dca9f91576a"),
                            Author = "Author14",
                            Category = "NonFiction",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN141520",
                            Publisher = "Publisher14",
                            PublishingDate = new DateTime(1923, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title14"
                        },
                        new
                        {
                            Id = new Guid("ee888428-cec9-415e-8f3c-e8c19d42cf67"),
                            Author = "Author15",
                            Category = "Romance",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN151621",
                            Publisher = "Publisher15",
                            PublishingDate = new DateTime(1946, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title15"
                        },
                        new
                        {
                            Id = new Guid("600003ea-5967-4c94-b722-ed551388d50e"),
                            Author = "Author16",
                            Category = "Horror",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN161722",
                            Publisher = "Publisher16",
                            PublishingDate = new DateTime(2015, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title16"
                        },
                        new
                        {
                            Id = new Guid("e0926594-c162-4cf9-9d0a-438935e43f50"),
                            Author = "Author17",
                            Category = "ForChildren",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN171823",
                            Publisher = "Publisher17",
                            PublishingDate = new DateTime(1921, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title17"
                        },
                        new
                        {
                            Id = new Guid("c8b9ca34-0f7f-4ce9-ab04-225606994fba"),
                            Author = "Author18",
                            Category = "Biography",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN181924",
                            Publisher = "Publisher18",
                            PublishingDate = new DateTime(1946, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title18"
                        },
                        new
                        {
                            Id = new Guid("30d5eb8b-38a8-44b8-95ff-e0cbd1753c1e"),
                            Author = "Author19",
                            Category = "Biography",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN192025",
                            Publisher = "Publisher19",
                            PublishingDate = new DateTime(1962, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title19"
                        },
                        new
                        {
                            Id = new Guid("ec105ce0-4cac-48c5-9073-f4ac72760ca2"),
                            Author = "Author20",
                            Category = "Poetry",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN202126",
                            Publisher = "Publisher20",
                            PublishingDate = new DateTime(1944, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title20"
                        },
                        new
                        {
                            Id = new Guid("9e98fefb-fcfa-4261-a2bf-fef6037bc105"),
                            Author = "Author21",
                            Category = "Romance",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN212227",
                            Publisher = "Publisher21",
                            PublishingDate = new DateTime(2017, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title21"
                        },
                        new
                        {
                            Id = new Guid("accd8c04-be53-48a5-8edf-48b9511efa37"),
                            Author = "Author22",
                            Category = "Biography",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN222328",
                            Publisher = "Publisher22",
                            PublishingDate = new DateTime(1950, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title22"
                        },
                        new
                        {
                            Id = new Guid("e3d7839c-37ad-49e1-8623-71e2dbecf48b"),
                            Author = "Author23",
                            Category = "Fantasy",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN232429",
                            Publisher = "Publisher23",
                            PublishingDate = new DateTime(1965, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title23"
                        },
                        new
                        {
                            Id = new Guid("5f96c41b-8ea3-464f-aac7-a909d74e3f48"),
                            Author = "Author24",
                            Category = "ForTeens",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN242530",
                            Publisher = "Publisher24",
                            PublishingDate = new DateTime(1941, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title24"
                        },
                        new
                        {
                            Id = new Guid("c7d7d629-1334-4552-ae82-de18ad4cab24"),
                            Author = "Author25",
                            Category = "ForTeens",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN252631",
                            Publisher = "Publisher25",
                            PublishingDate = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title25"
                        },
                        new
                        {
                            Id = new Guid("9d883ee7-5949-4332-b3d6-f6638e4a41f6"),
                            Author = "Author26",
                            Category = "Crime",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN262732",
                            Publisher = "Publisher26",
                            PublishingDate = new DateTime(2014, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title26"
                        },
                        new
                        {
                            Id = new Guid("bba37deb-7229-4115-a676-51588588535e"),
                            Author = "Author27",
                            Category = "ForChildren",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN272833",
                            Publisher = "Publisher27",
                            PublishingDate = new DateTime(1998, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title27"
                        },
                        new
                        {
                            Id = new Guid("8265cacb-ec8c-48b9-9333-e6378521030e"),
                            Author = "Author28",
                            Category = "Biography",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN282934",
                            Publisher = "Publisher28",
                            PublishingDate = new DateTime(1955, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title28"
                        },
                        new
                        {
                            Id = new Guid("8da7bee6-6642-4b4e-912b-3f7d3b1e9919"),
                            Author = "Author29",
                            Category = "Fantasy",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN293035",
                            Publisher = "Publisher29",
                            PublishingDate = new DateTime(1981, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title29"
                        },
                        new
                        {
                            Id = new Guid("1ff09596-a1fc-48aa-81c3-d5dc51ce7f8c"),
                            Author = "Author30",
                            Category = "Fantasy",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN303136",
                            Publisher = "Publisher30",
                            PublishingDate = new DateTime(2010, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title30"
                        },
                        new
                        {
                            Id = new Guid("ae5825ba-fb35-42c6-8cb8-0dade3cb3ac2"),
                            Author = "Author31",
                            Category = "Crime",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN313237",
                            Publisher = "Publisher31",
                            PublishingDate = new DateTime(1963, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title31"
                        },
                        new
                        {
                            Id = new Guid("75d3b25f-2b91-4183-b7c5-a8571222ad14"),
                            Author = "Author32",
                            Category = "Horror",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN323338",
                            Publisher = "Publisher32",
                            PublishingDate = new DateTime(2011, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title32"
                        },
                        new
                        {
                            Id = new Guid("d97f5cf6-5d14-4d88-94f1-c216951e0eb8"),
                            Author = "Author33",
                            Category = "Horror",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN333439",
                            Publisher = "Publisher33",
                            PublishingDate = new DateTime(2004, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title33"
                        },
                        new
                        {
                            Id = new Guid("50634792-2372-47c4-8201-8b702af6451d"),
                            Author = "Author34",
                            Category = "Biography",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN343540",
                            Publisher = "Publisher34",
                            PublishingDate = new DateTime(1990, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title34"
                        },
                        new
                        {
                            Id = new Guid("2ecf5b16-6e1b-4a99-bc01-20f6da1b71d8"),
                            Author = "Author35",
                            Category = "Romance",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN353641",
                            Publisher = "Publisher35",
                            PublishingDate = new DateTime(1999, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title35"
                        },
                        new
                        {
                            Id = new Guid("71c0dcf0-0fdd-4b68-b1d4-42a8b9511a0e"),
                            Author = "Author36",
                            Category = "ForChildren",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN363742",
                            Publisher = "Publisher36",
                            PublishingDate = new DateTime(1981, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title36"
                        },
                        new
                        {
                            Id = new Guid("d8dc7bda-4523-43ed-a4bf-4d880741faf2"),
                            Author = "Author37",
                            Category = "ForTeens",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN373843",
                            Publisher = "Publisher37",
                            PublishingDate = new DateTime(2021, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title37"
                        },
                        new
                        {
                            Id = new Guid("e773f306-c65d-48b4-b86b-08074aa3d111"),
                            Author = "Author38",
                            Category = "ForTeens",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN383944",
                            Publisher = "Publisher38",
                            PublishingDate = new DateTime(1932, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title38"
                        },
                        new
                        {
                            Id = new Guid("a8fb45c6-bc6e-47cb-aa66-a2eebfd7fdf0"),
                            Author = "Author39",
                            Category = "ForTeens",
                            DateAdded = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ISBNCode = "ISBN394045",
                            Publisher = "Publisher39",
                            PublishingDate = new DateTime(1945, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Free",
                            Title = "Title39"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
